### ISSUE TITLE
Guava version conflict

### ISSUE THREAD

**Issue by VicBing** [google/guice#1090]
Guice 4.1 is use guava 19 , but i need guava 21, how to deal with this conflict?

**Comment by dimo414** [comment]
In general Guava is fairly backwards-compatible, so you are probably able to use Guava 21 and Guice out of the box. If you're running into a specific issue please clarify what's failing. You can also update https://github.com/google/guice/blob/4e0cdc3/pom.xml#L147, test it, and send a pull request if you'd like.

**Comment by mcculls** [comment]
We're successfully running Guice 4.1 (core plus several extensions) with
Guava 21.0 - we use Maven's dependencyManagement in the project consuming
Guice to make sure everything uses the same version:

https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management

Can you provide more details about the conflict you're seeing?

On 28 Mar 2017 07:06, "VicBing" <notifications@github.com> wrote:

Guice 4.1 is use guava 19 , but i need guava 21, how to deal with this
conflict?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/guice/issues/1090>, or mute the thread

**Comment by agebhar1** [comment]
> In general Guava is fairly backwards-compatible, so you are probably able to use Guava 21 and Guice out of the box.

@dimo414 The problem I see are some edge cases which are not covered due to (unit) tests. Check by [Java API Compliance Checker](https://github.com/lvc/japi-compliance-checker):
![guava-19 21](https://user-images.githubusercontent.com/2443866/31238367-07cfe740-a9fa-11e7-8914-1d721c7bb563.png)
There are some removed methods which potentially lead to `NoSuchMethodException` during runtime.
