### ISSUE TITLE
put a binding in a separate thread , not blocking the main thread.

### ISSUE THREAD

**Issue by JasonHuangHuster** [google/guice#1105]
i have a time-cost object initialization ,   actually the object it self won't be used by others , but it depends on other Injected objects , so it has to be managed by guice . but now this time-cost object delay the whole launch time of my application , i tried to put the binding inside a separate thread . but it turns out a NPE .
`

    @Override
    protected void configure() {

        new Thread(new Runnable() {
            @Override
            public void run() {
                bind(ProducerManager.class).asEagerSingleton();

                if (KilimTool.isKilimMode()) {

                    bind(KilimConsumerManager.class).asEagerSingleton();
                } else {
                    bind(ConsumerManager.class).asEagerSingleton();
                }
            }
        }).start();
    }
`
![10ba39ba-c555-4ae2-ba72-364e5533d2ae](https://cloud.githubusercontent.com/assets/5965173/26565451/f6887bdc-451d-11e7-8edf-a0f3b872df09.png)

**Comment by dimo414** [comment]
The NPE is because [`AbstractModule` is not thread-safe](https://github.com/google/guice/blob/41f307e21b/core/src/com/google/inject/AbstractModule.java#L63), and you're attempting to call `bind()` (potentially) after injection is complete. This single-threaded behavior of Guice bindings isn't likely to change, so you should look for alternatives to doing expensive work in during injector-construction.

Instead of trying to concurrently add bindings, define a custom `Provider` for the binding and do the expensive work inside the provider. If the provider is bound with `.asEagerSingleton()` injector construction will still wait for the provider to return, but your provider can potentially dispatch work to multiple threads in order to return more quickly. Using `.in(Singleton.class)` instead will allow the injector to finish quickly, and only the first usages of the binding will need to block.
