### ISSUE TITLE
Protected Inner Class/Interface leads to failed compilation

### ISSUE THREAD

**Issue by tmquoc95** [google/guice#1278]
This is just dummy recreation of a bug that I found when I tried Guice
The EventBus needs an implementation of MessageHandler which is declared as inner interface in Watcher class. Guice was involved for latter AOP interceptor for logging

**EventBus.java**
```
public class EventBus {

	private MessageHandler<String> handler;

	public void setHandler(MessageHandler<String> handler) {
		this.handler = handler;
	}

	public void start() {
		String[] arr = {"ABC", "DEF", "GHI"};
		for (int i = 0; i < arr.length; i++) {
			String data = arr[i];
			handler.onEvent(i, data);
		}
	}
}

```
**Watcher.java**
```
public class Watcher {

	public abstract static class StringHandler implements MessageHandler<String> {
	}

	protected interface MessageHandler<T> {
		void onEvent(long eventId, T data);
	}
}
```

**HandlerImpl.java**
```
public class HandlerImpl extends Watcher.StringHandler {

	@Override
	public void onEvent(long eventId, String data) {
		System.out.printf("HandlerImpl: {eventId: %d, data:%s}%n", eventId, data);
	}
}

```
**MainApp.java**
```
public class MainApp {
	public static void main(String[] args) {
		Injector injector = Guice.createInjector(new AbstractModule() {
			@Override
			protected void configure() {

			}
		});

		EventBus eventBus = new EventBus();
		eventBus.setHandler(injector.getInstance(HandlerImpl.class));
		eventBus.start();
	}
}
```

**This code compiled with error** 
_error: MessageHandler has protected access in Watcher
eventBus.setHandler(injector.getInstance(HandlerImpl.class));_

(It must be compiled explicitly, my IntelliJ IDEA didn't not give any warning at first)

I was frustrated for an hour looking for cause of failed compliation. Then I was even more frustrated for figure out how a simple magical change makes everything work:

**MainApp.java**

```
public class MainApp {
	public static void main(String[] args) {
		Injector injector = Guice.createInjector(new AbstractModule() {
			@Override
			protected void configure() {

			}
		});

		EventBus eventBus = new EventBus();
		HandlerImpl impl = injector.getInstance(HandlerImpl.class);
		eventBus.setHandler(impl);
		eventBus.start();
	}
}
```

Might anyone explain this situation for me, please? Why was the meaningless variable assignment needed?

Big thanks for everyone. <3

**Comment by mcculls** [comment]
This isn't a bug in Guice, this is a result of how Java generic type parameters are resolved.

The `getInstance` method on the injector is declared as a generic method:
```
<T> T getInstance(Class<T> type);
```

Note that the type variable `T` applies to both the return value and the parameter. When the Java compiler tries to resolve this against the call in `MainApp` it sees that `setHandler` expects a `MessageHandler<String>` and `HandlerImpl` implements `MessageHandler<String>`:
```
eventBus.setHandler(injector.getInstance(HandlerImpl.class));
```
So it resolves the type variable to `MessageHandler<String>`. Unfortunately since `MessageHandler` is protected and it looks like you have `MainApp` in a different package, then `MainApp` cannot see this type and compilations fails.

When you change the call to:
```
HandlerImpl impl = injector.getInstance(HandlerImpl.class);
```
you change the constraints on the type variable. Now the compiler sees the result should be a `HandlerImpl` and since that matches the parameter, it now resolves the type to `HandlerImpl`. And because `HandlerImpl` is public, it is visible to `MainApp` and the compilation succeeds.

**Comment by tmquoc95** [comment]
@mcculls Thank you for your quick response. I really appreciated it.
