### ISSUE TITLE
Struts 6.x.x not working with Guice

### ISSUE THREAD

**Issue by hakan-andersson** [google/guice#1744]
In Struts version 6.x.x guice is not working, throws a NullPointerException in ValueStackFactory.

2023-05-17 12:26:56,680 ERROR [http-nio-8080-exec-30] dispatcher.DefaultDispatcherErrorHandler (DefaultDispatcherErrorHandler.java:87) - Exception occurred during processing request: Cannot invoke "com.opensymphony.xwork2.util.ValueStackFactory.createValueStack(com.opensymphony.xwork2.util.ValueStack)" because "this.valueStackFactory" is null
java.lang.NullPointerException: Cannot invoke "com.opensymphony.xwork2.util.ValueStackFactory.createValueStack(com.opensymphony.xwork2.util.ValueStack)" because "this.valueStackFactory" is null
    at com.opensymphony.xwork2.interceptor.ParametersInterceptor.setParameters(ParametersInterceptor.java:197) ~[classes/:6.1.2]
    at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:136) ~[classes/:6.1.2]

**Comment by chylek-qr** [comment]
Is there any fix or workaround for this?

**Comment by sameb** [comment]
There's no trace of Guice in this stack trace, and it's not clear how you're integration struts and Guice. Your question is probably best asked on whatever library is doing that integration for you.

**Comment by chylek-qr** [comment]
> There's no trace of Guice in this stack trace, and it's not clear how you're integrating struts and Guice. Your question is probably best asked on whatever library is doing that integration for you.

@sameb Guice is not injecting anything into Struts objects, so it's crashing with null pointer exceptions. It looks like Guice is ignoring Struts 6's Inject annotations.

**Comment by sameb** [comment]
I am not familiar with struts, and don't know what "struts 6's inject annotations" are. Guice requires:
 - Guice 5 and earlier: `com.google.inject.Inject` or `javax.inject.Inject`
 - Guice 6: `com.google.inject.Inject` or `javax.inject.Inject` or `jakarta.inject.Inject`
 - Guice 7+: `com.google.inject.Inject` or `jakarta.inject.Inject`
 
Guice does not support any other annotations indicating that something needs to be injected.

If the objects are annotated correctly but not being injected, then that means Guice isn't aware of them and doesn't know to inject them.  Both would problems with whatever is intending to integrate Struts & Guice, but not a problem with Guice itself.

**Comment by sameb** [comment]
Are you using the Guice struts2 extension for the integration?  What version of Guice are you using? 

See the "important" notice at the top of the struts2 extension wiki page. Guice 7 removed the struts2 extension, because struts2 doesn't support the new jakarta namespace. 

If you're using Guice 6 or earlier, then it's possible struts 6 broke the integration somehow. If struts 6 uses different inject annotations than what Guice expects, there's not much Guice can do to fix this.  What annotations are on fields/methods you expect to be injected?

**Comment by chylek-qr** [comment]
I'm using Guice 6 with the official extension for struts integration. The annotations appear to be a red herring, both struts 2.5.26 and 6.1.2 use`com.opensymphony.xwork2.inject.Inject` and they get injected with their own injector.

If I look at `com.opensymphony.xwork2.interceptor.StaticParametersInterceptor#setValueStackFactory` in struts 6.1.2, without Guice this method gets called on startup to inject `valueStackFactory`.

After including the Guice struts extension in Gradle and using `GuiceServletContextListener` and `GuiceFilter` as instructed, this method does not get called anymore and struts crashes because `valueStackFactory` is null.

**Comment by sameb** [comment]
@chylek-qr Please clarify if the following statements are true:
 * Guice 5's struts2 extension & Struts 5 work
 * Guice 6's struts2 extension & Struts 5 work
 * Guice 5 (or Guice 6)'s struts2 extension and Struts 6 does not work

If so, then this is indeed a problem with the struts2 extension. Unfortunately, I have no familiarity at all with struts, and will not be able to resolve the problems in the struts2 extension. Additionally, Guice 7 has dropped the struts2 extension, because struts doesn't support the jakarta servlet namespace (and Guice 7 only supports that servlet namespace).

If you'd like to try and debug what's going wrong with the https://github.com/google/guice/blob/master/extensions/struts2/src/com/google/inject/struts2/Struts2Factory.java and submit PRs (with tests), I can try to put out a patch release for Guice 6 that resolves this...  but absent that, I'm afraid the extension is likely to stop working with struts6+.

**Comment by chylek-qr** [comment]
Unfortunately I don't have much familiarity with struts either. I might try the combinations you mentioned later, I only tested Guice 6 which works in Struts2 version 2.5 but not in 6 (there are no versions 3-5 for some reason), but not Guice 5 with either Struts version.
