### ISSUE TITLE
Guice Servlet 3 multipart support?

### ISSUE THREAD

**Issue by stephanechorne** [google/guice#898]
Hi, I'm using embedded Jetty together with Guice and its Servlet extension.

Servlet 3 added multipart support (previously provided by [Apache Commons FileUpload](http://commons.apache.org/proper/commons-fileupload/)). Is there a way to programmatically configure this inside `ServletModule` using [MultipartConfigElement](http://docs.oracle.com/javaee/7/api/javax/servlet/MultipartConfigElement.html)?

Doing it in Jetty would look something like this:
``` java
ServletHolder holder = new ServletHolder(new MyServlet());
holder.getRegistration().setMultipartConfig(new MultipartConfigElement("/tmp", ...));
```

Thanks!

**Comment by Evkin** [comment]
For Jetty I use this hack:
```java
@Singleton
@MultipartConfig
public abstract class UploadServlet extends HttpServlet {
    private static final String __MULTIPART_CONFIG_ELEMENT = "org.eclipse.jetty.multipartConfig";     //todo - jetty 9

    @Override
    public void service(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
        if ("POST".equals(req.getMethod())) {
            req.setAttribute(__MULTIPART_CONFIG_ELEMENT, new MultipartConfigElement(""));
        }
        super.service(req, res);
    }
}
```

**Comment by stephanechorne** [comment]
Thanks, that did the trick!

**Comment by nsoft** [comment]
Why was this closed with a jetty specific hack?

**Comment by nsoft** [comment]
How should this be supported on Tomcat or TomEE? @stpch should this really be closed? It looks like @Evkin found a workaround for a specific server that helped you personally, but this still doesn't seem to be supported in Guice?

**Comment by nsoft** [comment]
After digging for a while I see that issue strikes at a fundamental issue in the way Guice configures servlets. Servlets are instantiated within and by an overarching `com.google.inject.servlet.GuiceFilter` and thus no matter how many servlets you install there is only going to be a single `jakarta.servlet.ServletRegistration` for a "default." One potential confusion arises if you left an @WebServlet annotation on your servlet class, the container may create a registration for it, but never serve anything via it because the Guice filter is handling the request first.

That all matters because at least in the case of tomcat, the `@MultipartConfig` is associated with the registration for that servlet. Since there's only one registration (for 'default'), the best you are going to be able to do is have one multipart config for all servlets... which means all servlets will be configured for multi-part (or none) and the will all have the same limit (i.e. `@MultipartConfig (maxFileSize = 10_000_000L)` would apply to every servlet in the application... 

Also the unattractive bit about the above hack for Jetty is of course that it's creating a new (garbage collectable) `MultipartConfigElement` every request... potentially solvable, but wasteful as shown...

I suspect I'm going to have to find a way to make the injector available, and have the servlet doing multi-part self inject in the init() method to work around this... if such a thing is possible...
