### ISSUE TITLE
BridgeClassLoader should implement BundleReference 

### ISSUE THREAD

**Issue by giamma** [google/guice#907]
OSGi applications can use FrameworkUtil.getBundle( Class<?> classFromBundle) to obtain a bundle given its class.

The above method should always return the class declaring bundle, unless the class is exported by the system bundle.

For classes enhanced by Guice AOP, the above method returns null. This happens because the BridgeClassLoader does not implement BundleReference, the OSGi specification interface that every classloader in an OSGi runtime should implement and which provides a method to obtain Bundle.

I believe that when running in an OSGi environment, Guice should not use BridgeClassLoader, but a decorator of the same which also implements BundleReference and whose getBundle() method delegates to the original class classloader.

```
OSGiBridgeClassLoader extends BridgeClassLoader implements BundleReference {

       
       public Bundle getBundle() {

                ClassLoader parent = getParent();
                if (parent instanceof BundleReference) {
                         return ((BundleReference)parent).getBundle();
                }

                return null;
       }
}
```

**Comment by sameb** [comment]
@mcculls -- you know best about this.  Any idea?

**Comment by mcculls** [comment]
This can happen any time you encounter proxying in OSGi. IMHO it would be more robust if the client code that's calling `FrameworkUtil.getBundle` detects the null response and tries the superclass. ie. similar to how it's a good idea to check the superclass when looking for method annotations, since they are not necessarily copied from the base class onto declared methods in the proxy class (it depends on the framework doing the proxying).

While it's technically possible to implement this in Guice, it won't help you if you have other frameworks that use Spring-based proxies - or other custom javassist/cglib proxies. That's why I believe the best solution is to make the client code more robust.

Also note that the javadoc for `FrameworkUtil.getBundle` states that it returns: "A Bundle for the specified bundle class or null if the specified class was not defined by a bundle class loader.". Since there could be many non-bundle classloaders in a system, client code should be prepared for the case that null is returned and act accordingly.

**Comment by sameb** [comment]
Since implementing this would require adding a new dependency and it seems client code is can workaround, I'm going to close.
