### ISSUE TITLE
Singleton scope on .toInstance() binding should be enabled by default

### ISSUE THREAD

**Issue by powerbroker** [google/guice#928]
The code
   this.bind(SomeType.class).toInstance(new SomeType());
in AbstractModule subclass causes default "inject-and-forget-instance" behavior. The singleton behavior should be instead since the instance itself(but not a type/constructor/etc.) is provided and there is no easy way to enforce Singleton behavior over .toInstance() binding. 

Guice version(MANIFEST.MF)
Bundle-Version: 4.0.0
Export-packages: com.google.inject.name;version="1.4",com.google.inject.binder;version="1.4",com.google.inject.spi;version="1.4",com.google.inject.matcher;version="1.4",com.google.inject.util;version="1.4",com.google.inject;version="1.4"

**Comment by sameb** [comment]
Do you have a test showing it behaves this way?  It shouldn't (and AFAIK doesn't).

**Comment by powerbroker** [comment]
Here is the simple Eclipse project demonstrating this.

**Comment by sameb** [comment]
This is a bit confusing, but is WAI.  You can see the issue more clearly if you add a call to `binder().requireExplicitBindings()`.

 The problem is you're binding `Foo.class` but then injecting `Foo<Type>`.  `Foo` and `Foo<Type>` are two different things -- Guice doesn't know anything's bound to `Foo<Type>` and tries to create a just-in-time binding for it (resolving to the class & seeing no scoping annotation on it, so creating a new one each time).

**Comment by powerbroker** [comment]
Maybe you have an idea how to bind Foo<Type>?

**Comment by sameb** [comment]
`bind(new TypeLiteral<Foo<Type>>() {}` -- see the Binder javadoc @ http://google.github.io/guice/api-docs/latest/javadoc/index.html?com/google/inject/Binder.html, specifically the part that mentions TypeLiteral.

The weird syntax is unfortunately required because otherwise the generics data is erased.

**Comment by sameb** [comment]
Also, `@Provides` methods make this a little simpler, just have a method:
```
  @Provides Foo<Type> provideFoo() { return new MyFoo(); }
```

**Comment by powerbroker** [comment]
Thx. It seems @Provides method must be annotated with @Singleton or reuse cached instance to enforce singleton behavior.
