### ISSUE TITLE
Binding an implicit implementation with a qualifier

### ISSUE THREAD

**Issue by BrynCooke** [google/guice#946]
Binding an implicit implementation seems to be possible without a qualifier, but adding a qualifier means the target of the binding must be specified. This caused a little head scratching.

```

    public static class A {

    }

    @Retention(RetentionPolicy.RUNTIME)
    @BindingAnnotation
    public @interface MyQualifier {

    }

    @Test
    public void test() {
        Guice.createInjector(new Module() {

            @Override
            public void configure(Binder binder)
            {
                binder.requireExplicitBindings();
                binder.bind(A.class); //This is OK.
                binder.bind(A.class).annotatedWith(MyQualifier.class); //Why is this not OK?
                //binder.bind(A.class).annotatedWith(MyQualifier.class).to(A.class); //This is OK.
            }
        });
    }

```

```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for test.GuiceTest$A annotated with interface test.GuiceTest$MyQualifier was bound.
  at test.GuiceTest$1.configure(GuiceTest.java:42)
```

**Comment by mcculls** [comment]
Correct, as mentioned on the wiki: _"When specifying binding annotations, you must still add the target binding, even it is the same concrete class."_ https://github.com/google/guice/wiki/UntargettedBindings

This is because declaring a qualified binding key and then not binding it to something is more often than not a programming mistake. It's also easier to read/follow qualified bindings when they have an explicit target.

**Comment by sameb** [comment]
This is WAI.
