### ISSUE TITLE
InstanceBinding - annotating class as @Singleton is not the same as binding #in(Singleton.class)

### ISSUE THREAD

**Issue by vantuz-subhuman** [google/guice#955]
##### Guice 4.0
I created one interface and one class implementing it:
```
class A implements I {}
interface I {}
```
Then I create injectors like this:
```
Injector injector1 = Guice.createInjector();
		
Module mod = b -> b.bind(I.class).to(A.class).in(Singleton.class);
Injector injector2a = injector1.createChildInjector(mod);
Injector injector2b = injector1.createChildInjector(mod);
		
System.out.println(injector2a.getInstance(I.class));
System.out.println(injector2a.getInstance(I.class));
System.out.println(injector2b.getInstance(I.class));
System.out.println(injector2b.getInstance(I.class));
```
Output is something like:
```
A@cb644e
A@cb644e
A@56ef9176
A@56ef9176
```
As expected - each child injector creates it's own singleton.
But then - if I annotate class `A` with `@Singleton`, output changes to something like:
```
A@1ed4004b
A@1ed4004b
A@1ed4004b
A@1ed4004b
```
Now both parallel child injectors provide me the same instance of a class. This behavior does not change if I remove `.in(Singleton.class)` part.

**But** this happens only with `InstanceBinding`. If I change code to this:
```
Injector injector1 = Guice.createInjector();
		
Module mod = b -> b.bind(A.class).in(Singleton.class);
Injector injector2a = injector1.createChildInjector(mod);
Injector injector2b = injector1.createChildInjector(mod);
		
System.out.println(injector2a.getInstance(A.class));
System.out.println(injector2a.getInstance(A.class));
System.out.println(injector2b.getInstance(A.class));
System.out.println(injector2b.getInstance(A.class));
```
And class `A` still annotated with `@Singleton`, output is valid:
```
A@1ed4004b
A@1ed4004b
A@5702b3b1
A@5702b3b1
```

**Comment by sameb** [comment]
This is WAI.  What's happening is:

`b.bind(I.class).to(A.class).in(Singleton.class);` is saying: Link I to A and make that link a singleton.  It has no impact on "A" being a singleton.  You can validate this by trying to get multiple instances of `A` and noting that each one will be different.  It's only when you get `I` that they're the same, because `I` is the singleton part.

So, what's happening with `b.bind(I.class).to(A.class).in(Singleton.class);` is the system says, "You want to bind I to A in the child injector as a singleton, great!".  Then it tries to go find `A` and says, "Oops, I don't have a binding for `A` yet, so let me create one just-in-time."  Guice creates just-in-time bindings in the parent-most injector, so `A` is created in the parent.

You can validate that "A" is in the parent by adding `injector1.getInstance(A.class)` -- it will succeed and give you an "A".

However, when "A" is marked `@Singleton`, then it doesn't matter that the `I->A` links are singletons, because A itself will always be the same.  The child injectors have the `I->A` links, and the parent has the just-in-time binding for `A`.

Now, if you change this by just saying `bind(A.class).in(Singleton.class)`, then you're explicitly binding A in the child injector.  So there's no just-in-time binding in the parent injector.  You can validate this by trying `injector1.getInstance(A.class)` again -- it will fail saying that the binding exists in a child injector.  (Guice won't let a binding exist in both a parent and a child.)

You can alter some of this behavior by using Binder.requireExplicitBindings() -- this will prevent Guice from creating just-in-time bindings.

**Comment by vantuz-subhuman** [comment]
Thanks for detailed explanation! Got it all now.
